import { Link } from "react-router-dom";

function Home() {
return (
<div
style={{
minHeight: "100vh",
background:
"linear-gradient(135deg, #0f172a, #1e293b, #111827)",
color: "white",
fontFamily: "Arial, sans-serif",
}}
>
<nav
style={{
display: "flex",
justifyContent: "space-between",
alignItems: "center",
padding: "20px 50px",
background: "rgba(255,255,255,0.05)",
backdropFilter: "blur(10px)",
borderBottom: "1px solid rgba(255,255,255,0.1)",
}}
>
<h2
style={{
margin: 0,
color: "#60a5fa",
}}
>
AI Interview Coach </h2>

```
    <div>
      <Link
        to="/"
        style={{
          marginRight: "20px",
          textDecoration: "none",
          color: "white",
          fontWeight: "bold",
        }}
      >
        Home
      </Link>

      <Link
        to="/dashboard"
        style={{
          textDecoration: "none",
          color: "white",
          fontWeight: "bold",
        }}
      >
        Dashboard
      </Link>
    </div>
  </nav>

  <div
    style={{
      textAlign: "center",
      paddingTop: "140px",
      maxWidth: "900px",
      margin: "auto",
    }}
  >
    <h1
      style={{
        fontSize: "58px",
        marginBottom: "20px",
        lineHeight: "1.2",
      }}
    >
      AI-Powered Interview
      <br />
      Preparation Platform
    </h1>

    <p
      style={{
        fontSize: "22px",
        color: "#cbd5e1",
        marginBottom: "40px",
      }}
    >
      Practice Python, Java, Data Science and HR interviews
      with intelligent AI-generated questions and detailed
      performance feedback.
    </p>

    <div
      style={{
        display: "flex",
        justifyContent: "center",
        gap: "20px",
        flexWrap: "wrap",
      }}
    >
      <Link to="/interview">
        <button
          style={{
            background: "#2563eb",
            color: "white",
            padding: "16px 35px",
            fontSize: "18px",
            border: "none",
            borderRadius: "10px",
            cursor: "pointer",
            fontWeight: "bold",
            boxShadow:
              "0 10px 25px rgba(37,99,235,0.4)",
          }}
        >
          Start Interview →
        </button>
      </Link>

      <Link to="/resume-interview">
        <button
          style={{
            background: "#16a34a",
            color: "white",
            padding: "16px 35px",
            fontSize: "18px",
            border: "none",
            borderRadius: "10px",
            cursor: "pointer",
            fontWeight: "bold",
            boxShadow:
              "0 10px 25px rgba(22,163,74,0.4)",
          }}
        >
          Upload Resume →
        </button>
      </Link>
    </div>

    <div
      style={{
        display: "flex",
        justifyContent: "center",
        gap: "30px",
        marginTop: "80px",
        flexWrap: "wrap",
      }}
    >
      <div
        style={{
          background: "rgba(255,255,255,0.08)",
          padding: "25px",
          borderRadius: "15px",
          width: "220px",
        }}
      >
        <h3>🤖 AI Questions</h3>
        <p>Dynamic interview questions generated by Gemini AI.</p>
      </div>

      <div
        style={{
          background: "rgba(255,255,255,0.08)",
          padding: "25px",
          borderRadius: "15px",
          width: "220px",
        }}
      >
        <h3>📊 Smart Feedback</h3>
        <p>Get scores, strengths, weaknesses and improvements.</p>
      </div>

      <div
        style={{
          background: "rgba(255,255,255,0.08)",
          padding: "25px",
          borderRadius: "15px",
          width: "220px",
        }}
      >
        <h3>🏆 Performance Tracking</h3>
        <p>Monitor interview progress through analytics.</p>
      </div>
    </div>
  </div>
</div>

);
}

export default Home;
